#!/usr/bin/env bash
# Script to start the local dev server

set -e

# Check if we have a cached version of RunDevServer, and run lorri if not
if ! lorri shell --cached
then
    lorri watch --once
fi

# Now we have to load the PATH variable from the .envrc cache
direnv allow
eval "$(direnv hook bash)"
eval "$(direnv export bash)"

# We start lorri to automatically update the dev environment
# NB: Only run lorri watch if the lorri daemon isn't active
if ! pgrep -f "lorri daemon"
then
    lorri watch &
    trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
fi

# We start the dev server that we have in our environment
RunDevServer
