# Autogenerated hardware config
# Run 'nixos-generate-config' on the deployment host to generate it
{ config, lib, pkgs, modulesPath, ... }:

{
    imports = [
        # For AWS EC2: "${inputs.nixpkgs}/nixos/modules/virtualisation/amazon-image.nix"
    ];

    # For testing purposes only, remove on bootable hosts.
    boot.loader.grub.enable = pkgs.lib.mkDefault false;
    fileSystems."/".device = pkgs.lib.mkDefault "/dev/null";
}
